# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

User.create!(name: "Joao", last_name: 'dos Santos', email:'joao123@gmail.com', password:'123456', is_admin: true)
User.create!(name: "Matheus", last_name: 'das Neves', email:'matheus123@gmail.com', password:'123456', is_admin: true)

Category.create(title: "Programação", description: 'Neste espaço, mergulharemos no mundo da programação, onde códigos de computador ganham vida para criar aplicativos, websites e soluções tecnológicas inovadoras. Descubra como linguagens de programação, algoritmos e estruturas de dados se combinam para resolver problemas complexos e moldar o futuro digital.')
Category.create(title: "Games", description: 'Bem-vindo ao universo dos jogos, onde a diversão encontra a estratégia e a competição. Explore diferentes plataformas, desde videogames até jogos de tabuleiro, enquanto mergulha em desafios emocionantes. Venha conhecer as mais diversas experiências de entretenimento interativo que este espaço tem a oferecer.')
Category.create(title: "Política", description: 'Adentre o cenário da política e desvende os meandros da governança, das políticas públicas e da participação cívica. Neste espaço, exploraremos os sistemas de poder, as tomadas de decisões e as implicações sociais que moldam nossa sociedade. Prepare-se para compreender o mundo da política de forma aprofundada e informada.')
Category.create(title: "Filmes", description: 'Aqui, convidamos você a explorar o mundo mágico do cinema. De dramas envolventes a aventuras cheias de ação, cada projeção oferece uma janela para narrativas cativantes e visuais impressionantes. Navegue pelas telas e descubra como os filmes não apenas entretêm, mas também refletem a diversidade da experiência humana.')

Post.create(title: "HTML", description: "HTML é uma linguagem de marcação usada para estruturar o conteúdo de uma página da web. Ele define os elementos e a hierarquia de um documento, como parágrafos, cabeçalhos, listas, links, imagens e outros elementos. É a base de uma página da web e fornece a estrutura básica para exibir informações no navegador.", user_id: 1).post_image.attach(io: File.open('./public/assets/images/html.jpg'), filename:('html.jpg'))
PostCategory.create(post_id: 1, category_id: 1)
Post.create(title: "CSS", description: "CSS é uma linguagem de estilo usada para controlar a apresentação visual de uma página da web. Com CSS, você pode definir cores, fontes, margens, espaçamento, layout e outros aspectos de design. Ele permite separar a estrutura (HTML) do estilo (CSS) de uma página, facilitando a manutenção e a criação de páginas visualmente atraentes.", user_id: 2).post_image.attach(io: File.open('./public/assets/images/css.jpg'), filename:('css.jpg'))
PostCategory.create(post_id: 2, category_id: 1)
Post.create(title: "JavaScript", description: "JavaScript é uma linguagem de programação usada para adicionar interatividade e dinamismo a páginas da web. Com JavaScript, você pode criar comportamentos e funcionalidades interativas, como animações, validação de formulários, atualizações em tempo real e muito mais. Ele é executado no navegador do usuário e é uma parte essencial da experiência interativa na web moderna.", user_id: 1).post_image.attach(io: File.open('./public/assets/images/js.jpg'), filename:('js.jpg'))
PostCategory.create(post_id: 3, category_id: 1)

Post.create(title: "League of Legends, atualizações recentes", description: "League of Legends é um popular jogo MOBA (Multiplayer Online Battle Arena) desenvolvido pela Riot Games. As atualizações frequentes do jogo incluem ajustes de balanceamento de campeões, itens e mecânicas de jogo, além de introduzir novos recursos, skins e eventos sazonais. Essas atualizações buscam manter o jogo competitivo, diversificado e atraente para os jogadores.", user_id: 2).post_image.attach(io: File.open('./public/assets/images/lol.jpeg'), filename:('lol.jpeg'))
PostCategory.create(post_id: 4, category_id: 2)
Post.create(title: "Valorant, novas skins", description: "Valorant é um jogo de tiro tático em primeira pessoa desenvolvido pela Riot Games. Regularmente, novas skins e coleções de armas são introduzidas no jogo, oferecendo aos jogadores a oportunidade de personalizar suas armas com estilos exclusivos. Essas skins muitas vezes são temáticas e podem ser obtidas através de compras no jogo ou recompensas de eventos.", user_id: 1).post_image.attach(io: File.open('./public/assets/images/vava.png'), filename:('vava.png'))
PostCategory.create(post_id: 5, category_id: 2)
Post.create(title: "CS:GO, nova versão é lancada", description: "Até a minha data de corte em setembro de 2021, não havia informações sobre uma nova versão do CS:GO. No entanto, é importante mencionar que o CS:GO é um jogo de tiro em primeira pessoa altamente popular, desenvolvido pela Valve. Atualizações regulares do jogo incluem correções de bugs, melhorias de desempenho, ajustes de balanceamento de armas e mapas, além de eventos sazonais que podem trazer novas mecânicas de jogo e conteúdo temático.", user_id: 2).post_image.attach(io: File.open('./public/assets/images/cs.png'), filename:('cs.png'))
PostCategory.create(post_id: 6, category_id: 2)

Post.create(title: "EUA, hostilidade com Rússia após guerra", description: "As relações entre os Estados Unidos e a Rússia têm sido marcadas por períodos de tensão e cooperação ao longo do tempo. Hostilidades podem surgir devido a questões geopolíticas, disputas territoriais, questões de segurança, cibersegurança e outros fatores. Sanções econômicas, expulsões de diplomatas e retórica forte são algumas das manifestações da tensão entre os dois países.", user_id: 1).post_image.attach(io: File.open('./public/assets/images/eua.jpg'), filename:('eua.jpg'))
PostCategory.create(post_id: 7, category_id: 3)
Post.create(title: "Eleições Brasil, a maior polaridade das últimas décadas", description: "As eleições no Brasil têm demonstrado polarização política significativa nos últimos anos. Divergências ideológicas, questões sociais, econômicas e culturais têm contribuído para uma divisão acentuada entre os eleitores e partidos políticos. Esse cenário polarizado pode afetar o tom das campanhas eleitorais, debates públicos e até mesmo a governabilidade pós-eleição.", user_id: 2).post_image.attach(io: File.open('./public/assets/images/brasil.jpg'), filename:('brasil.jpg'))
PostCategory.create(post_id: 8, category_id: 3)
Post.create(title: "El Salvador, nova política contra corrupção", description: "El Salvador implementou medidas políticas anti corrupção como parte de esforços para combater a corrupção no governo e nas instituições. Essas políticas podem envolver a criação de agências independentes de fiscalização, reformas legais e judiciais, investigações de casos de corrupção de alto nível e a promoção da transparência e responsabilidade no governo. Essas ações visam fortalecer as instituições e melhorar a governança no país.", user_id: 1).post_image.attach(io: File.open('./public/assets/images/elsalvador.jpg'), filename:('elsalvador.jpg'))
PostCategory.create(post_id: 9, category_id: 3)

Post.create(title: "O filme Openheimer é lancado nos cinemas", description: "Oppenheimer é um filme histórico de drama dirigido por Christopher Nolan e baseado no livro biográfico vencedor do Prêmio Pulitzer, Prometeu Americano: O Triunfo e a Tragédia de J. Robert Oppenheimer, escrito por Kai Bird e Martin J. Sherwin. Ambientado na Segunda Guerra Mundial, o longa acompanha a vida de J. Robert Oppenheimer (Cillian Murphy), físico teórico da Universidade da Califórnia e diretor do Laboratório de Los Alamos durante o Projeto Manhattan - que tinha a missão de projetar e construir as primeiras bombas atômicas.", user_id: 2).post_image.attach(io: File.open('./public/assets/images/openheimer.jpg'), filename:('openheimer.jpg'))
PostCategory.create(post_id: 10, category_id: 4)
Post.create(title: "Barbie é destaque nas redes sociais", description: "O filme Barbie, que estreou na última semana no Brasil, gerou grande movimentação nas redes sociais por parte das marcas, influencers e veículos. Isso é que mostra dados do Buzzmonitor Trends, ferramenta da plataforma de monitoramento e atendimento multicanal Buzzmonitor.Em um mês, de 26 de junho a 26 de julho, o levantamento mostra que foram publicados mais de 1.045.738 posts com os termos “barbie”, “#barbie” ou “#barbieofilme” nas redes sociais de veículos e influenciadores, em português.", user_id: 1).post_image.attach(io: File.open('./public/assets/images/barbie.jpg'), filename:('barbie.jpg'))
PostCategory.create(post_id: 11, category_id: 4)
Post.create(title: "Vingadores sempre vai ser a melhor saga", description: "A saga dos Vingadores, parte do Universo Cinematográfico Marvel (MCU), é amplamente considerada por muitos fãs e críticos como uma das melhores sagas cinematográficas. Ela engloba vários filmes interconectados, apresentando uma variedade de super-heróis e histórias que culminam em batalhas épicas e momentos emocionantes. A popularidade do MCU e dos Vingadores é evidente pelo sucesso de bilheteria e pelo impacto cultural que a franquia teve ao longo dos anos.", user_id: 2).post_image.attach(io: File.open('./public/assets/images/vingadores.jpeg'), filename:('vingadores.jpeg'))
PostCategory.create(post_id: 12, category_id: 4)